name: Docker Build -> Push -> Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '25'

    - name: Build Jar
      run: ./mvnw clean package -DskipTests

    - name: Login to DockerHub
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-cicd:latest

    - name: Push the Docker Image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/springcicd:latest

    - name: Deploy to EC2 using SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker stop springcicd-demo || true
          docker rm springcicd-demo
          docker pull ${{ secrets.DOCKER_USERNAME }}/springcicd:latest
          docker run -d --name springcicd-demo -p 9091:9091 ${{ secrets.DOCKER_USERNAME }}/springcicd:latest
    
